# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - ctfonline.md
  - about.md
  - contact.md
  - resume.md

footer: 'follow me on <a href="https://twitter.com/fareedfauzi_">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
