# Site settings
title: Fareed Fauzi
description: Resume of Fareed Fauzi
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fareed Fauzi
user_description: I'm a nomad Security Researcher, always searching for the next challenge; no task is too scary nor too difficult. I'm interested in reverse code engineering, malware analysis and forensics. Lately I have been immersed in the <b>AWL bypass</b> with working for Cyseca department at Pernec Integrated Services Sdn. Bhd., a Kuala Lumpur based startup trying to create the next massive endpoint protection. I'm one of the guys does researching on security related stuff. Visit my blog here <a href="https://fareedfauzi.github.io" target="_blank">https://fareedfauzi.github.io</a>
user_title: Security Researcher
email: fareedradzi@gmail.com
twitter_username: fareedfauzi_
github_username:  fareedfauzi
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
